spring.application.name=developersb_submission

# アプリ起動時にプロジェクト直下の「data/mydb」フォルダにデータを自動保存する設定
spring.datasource.url=jdbc:h2:file:~/data/mydb;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# HibernateにH2データベースを使っていることを明示（自動判別されますが明示すると確実です）
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# アプリ起動時に自動でテーブルを生成・更新する設定
spring.jpa.hibernate.ddl-auto=update

# Webコンソールを有効化
spring.h2.console.enabled=true
# パスの指定（デフォルトは /h2-console）
spring.h2.console.path=/h2-console
spring.jpa.open-in-view=false

# 実行されるSQLをログに出力して確認できるようにする
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security=DEBUG